# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Contact: /contact
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- links
- category
#- tag
- tagcloud
- archive
- recent_posts


# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

links:
- title: "Family photos"
  url: http://www.culpabledistraint.net/photos
  intro: "Curated family photos"
  icon: "fa fa-external-link"
- title: "Curated links"
  url: /links
  intro: "My curated links"
  icon: "fa fa-link"
- title: "News river (River5)"
  url: http://54.167.172.54:1337/
  intro: My River5 rivers
  icon: "fa fa-external-link"