# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Contact: /contact
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
#- tag
- tagcloud
- archive
- recent_posts
- links

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

links:
- title: "Curated links"
  url: /links
  intro: "My curated links"
  icon: "fa fa-link"
- title: "Hexo"
  url: http://hexo.io
  intro: "My Linkin account."
  icon: "fa fa-share"
